version: '3.8'

services:
  app:
    container_name: weather-api-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=5000
    ports:
      - 5000:5000
