name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [master, develop]

jobs:
  test-ci:
    uses: ./test.yml

  deploy-test:
    needs: test-ci
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-test
    environment: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker build -t weather-api-nodejs .
      - run: echo "Deploy"

  deploy-production:
    needs: test-ci
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    concurrency: deploy-to-production
    environment: production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: docker build -t weather-api-nodejs .
      - run: echo "Deploy"
